/* CodePlatform main engine v1.3.0 */
'use strict';

const DEFAULT_ARENA_W=720, DEFAULT_ARENA_H=360, PLAYER_W=28, PLAYER_H=28;
const FIXED_DT=1/60, MAX_FRAME_DT=.1, MAX_STEPS_PER_FRAME=6;
const GRAVITY=.55, JUMP_VEL=-12, MOVE_SPD=3.8, MAX_FALL=18;
const PLAYER_HITBOX={x:2,y:2,w:24,h:24};
const LEVEL_BASE='data/levels/';
const BGM_SRC='audio/background.opus';

let stages=[];
let customStages=loadJSONStorage('cp_custom_stages',[]);
let currentStageIndex=0, currentStage=null, currentStageId=null;
let deathCount=0, runCount=0;
let completedStages=new Set(loadJSONStorage('cp_completed',[]));
let player={x:0,y:0,vx:0,vy:0,onGround:false,dead:false,rotation:0};
let keys={}, jumpQueued=false, animFrame=null, gameRunning=false, invincible=false;
let physicsAccumulator=0,lastFrameTime=0,inputMode=localStorage.getItem('cp_input_mode')||'play';
let playtestOrigin=null;
let customEditor={id:null,title:'My Custom Stage',diff:'medium',description:'Buat jalurmu sendiri.',arena:{width:720,height:360},objects:[],selected:null,tool:'edit',placeKind:'solid',spawn:{x:34,y:272},goal:{x:620,y:246}};
let editorHistory=[], editorHistoryIndex=-1, editorClipboard=null, editorDragging=false;

const $=id=>document.getElementById(id);
const arena=$('arena'), playerEl=$('player'), goalEl=$('goal'), spawnEl=$('spawn-marker'), userEls=$('user-elements');
const deathFlash=$('death-flash'), statusDot=$('status-dot'), statusText=$('status-text'), coordsEl=$('coords');
const deathCountEl=$('death-count'), runCountEl=$('run-count'), stageNameEl=$('stage-name'), stageLabelEl=$('stage-label'), stageHintEl=$('stage-hint');
const codeInput=$('code-input'), lineNumbers=$('line-numbers'), warnBanner=$('warn-banner'), warnText=$('warn-text');
const bgm=$('bgm');

function loadJSONStorage(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x??fallback}catch{return fallback}}
function saveProgress(){localStorage.setItem('cp_completed',JSON.stringify([...completedStages]));}
function saveCustomStages(){localStorage.setItem('cp_custom_stages',JSON.stringify(customStages));}
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.remove('show'),2200)}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function deepClone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function getArenaSize(stage=currentStage){return{width:Number(stage?.arena?.width)||DEFAULT_ARENA_W,height:Number(stage?.arena?.height)||DEFAULT_ARENA_H}}
function setArenaDOMSize(stage){const s=getArenaSize(stage);arena.style.width=s.width+'px';arena.style.height=s.height+'px';}

/* ---------- NAVIGATION ---------- */
const screens=['home-screen','stage-screen','tutorial-screen','settings-screen','editor-screen','game-screen'];
function showScreen(id){screens.forEach(s=>{const el=$(s);if(el)el.classList.toggle('hidden',s!==id)});if(id!=='game-screen')stopGame();if(id==='game-screen'){requestAnimationFrame(()=>requestAnimationFrame(rescaleArena));}}
function showHome(){playtestOrigin=null;showScreen('home-screen')}
function showStageScreen(){playtestOrigin=null;showScreen('stage-screen');buildStageGrid();buildCustomStageGrid()}
function showTutorialScreen(){showScreen('tutorial-screen')}
function showSettingsScreen(){showScreen('settings-screen');syncSettingsUI()}
function showEditorScreen(){playtestOrigin=null;showScreen('editor-screen');renderEditor()}
function backFromGame(){if(currentStage?.custom&&playtestOrigin==='editor'){showScreen('editor-screen');renderEditor();return}showStageScreen()}

/* ---------- THEME + AUDIO ---------- */
let isDark=localStorage.getItem('cp_theme')!=='light';
let bgmEnabled=localStorage.getItem('cp_bgm')==='on';
let bgmVolume=clamp(Number(localStorage.getItem('cp_bgm_volume') ?? .45),0,1);
function applyTheme(){document.documentElement.setAttribute('data-theme',isDark?'dark':'light');if($('theme-icon'))$('theme-icon').textContent=isDark?'🌙':'☀️';if($('theme-label'))$('theme-label').textContent=isDark?'Dark':'Light';localStorage.setItem('cp_theme',isDark?'dark':'light');syncSettingsUI()}
function toggleTheme(){isDark=!isDark;applyTheme()}
function syncSettingsUI(){if($('settings-theme-icon'))$('settings-theme-icon').textContent=isDark?'🌙':'☀️';if($('settings-theme-label'))$('settings-theme-label').textContent=isDark?'Dark':'Light';$('settings-play')?.classList.toggle('active',inputMode==='play');$('settings-code')?.classList.toggle('active',inputMode==='code');$('settings-bgm')?.classList.toggle('active',bgmEnabled);$('settings-bgm-state')?.replaceChildren(document.createTextNode(bgmEnabled?'On':'Off'));const slider=$('settings-bgm-volume');if(slider)slider.value=String(Math.round(bgmVolume*100));const output=$('settings-bgm-volume-value');if(output)output.textContent=Math.round(bgmVolume*100)+'%'}
function prepareBgm(){if(!bgm)return;if(bgm.src!==location.href+BGM_SRC && !bgm.src.endsWith('/'+BGM_SRC))bgm.src=BGM_SRC;bgm.loop=true;bgm.volume=bgmVolume}
function setBgmVolume(value){bgmVolume=clamp(Number(value)/100,0,1);localStorage.setItem('cp_bgm_volume',String(bgmVolume));if(bgm)bgm.volume=bgmVolume;const output=$('settings-bgm-volume-value');if(output)output.textContent=Math.round(bgmVolume*100)+'%';const slider=$('settings-bgm-volume');if(slider && slider.value!==String(Math.round(bgmVolume*100)))slider.value=String(Math.round(bgmVolume*100))}
function syncBgm(){if(!bgm)return;bgmEnabled=!!bgmEnabled;localStorage.setItem('cp_bgm',bgmEnabled?'on':'off');syncSettingsUI();if(!bgmEnabled){bgm.pause();return;}prepareBgm();const p=bgm.play();if(p?.catch)p.catch(()=>toast('Backsound aktif, tetapi browser menunggu interaksi.'))}
function toggleBgm(){bgmEnabled=!bgmEnabled;syncBgm()}

/* ---------- LEVEL LOADING ---------- */
async function loadAllStages(){
  try{
    const mr=await fetch(LEVEL_BASE+'manifest.json',{cache:'no-store'});if(!mr.ok)throw new Error(`manifest.json: HTTP ${mr.status}`);
    const manifest=await mr.json();
    if(!Array.isArray(manifest.levels))throw new Error('manifest.json tidak memiliki array "levels".');
    const results=await Promise.allSettled(manifest.levels.map(async file=>{const r=await fetch(LEVEL_BASE+file,{cache:'no-store'});if(!r.ok)throw new Error(`${file}: HTTP ${r.status}`);const data=await r.json();return{file,data}}));
    const failures=results.filter(r=>r.status==='rejected');
    stages=results.filter(r=>r.status==='fulfilled').map(r=>r.value.data).filter(s=>s&&Number.isFinite(Number(s.id))).sort((a,b)=>Number(a.id)-Number(b.id));
    if(!stages.length)throw new Error('Tidak ada level JSON yang berhasil dimuat.');
    if(failures.length)console.warn('[CodePlatform] Some levels failed:',failures.map(x=>x.reason?.message||x.reason));
    buildStageGrid();setStatus(`Level database: ${stages.length} loaded`,'ok');
  }catch(err){console.error('[CodePlatform] Level loader error:',err);stages=[];buildStageGrid();setStatus('Gagal memuat JSON level','dead');toast('Gagal memuat database level. Cek Console/Network.');}
}
function stageDifficultyClass(diff){return diff==='easy'?'diff-easy':diff==='hard'?'diff-hard':'diff-med'}
function isStageUnlocked(index){if(index<=0)return true;const prev=stages[index-1];return !!prev&&(completedStages.has(String(prev.id))||completedStages.has(prev.id))}
async function loadStage(index,options={}){if(index<0||index>=stages.length||!isStageUnlocked(index))return false;const preserveCode=!!options.preserveCode;currentStageIndex=index;currentStage=deepClone(stages[index]);currentStageId=String(currentStage.id);playtestOrigin=null;deathCount=0;runCount=0;deathCountEl.textContent='0';runCountEl.textContent='0';if(!preserveCode)codeInput.value='';updateLineNumbers();closeWarn();hideAC();renderStage(currentStage);showScreen('game-screen');focusGame();startGame();return true}
function loadCustomStage(stage,origin='stage-list'){currentStage=deepClone(stage);currentStageId=String(currentStage.id);currentStageIndex=-1;playtestOrigin=origin;deathCount=0;runCount=0;deathCountEl.textContent='0';runCountEl.textContent='0';codeInput.value='';updateLineNumbers();renderStage(currentStage);showScreen('game-screen');focusGame();startGame()}
function renderStage(stage){setArenaDOMSize(stage);stageNameEl.textContent=`${stage.custom?'★ ':''}${stage.id}. ${stage.title}`;stageLabelEl.textContent=stage.custom?'Custom Stage':`Stage ${stage.id}/${stages.length}`;stageHintEl.innerHTML=`<strong>💡 Petunjuk:</strong> ${stage.hint||stage.description||'Bangun jalur yang aman.'}`;arena.querySelectorAll('.stage-obj').forEach(e=>e.remove());userEls.innerHTML='';for(const obj of(stage.objects||[])){if(obj?.kind==='diamond')continue;createStageObject(obj)}const g=stage.goal||{};goalEl.style.left=(Number(g.x)||640)+'px';goalEl.style.top=(Number(g.y)||60)+'px';goalEl.style.transform=`rotate(${Number(g.angle)||0}deg)`;syncSpawnMarker();spawnPlayer();rescaleArena()}
function createStageObject(o){const el=document.createElement('div');const x=Number(o.x)||0,y=Number(o.y)||0,w=Number(o.w)||100,h=Number(o.h)||20,angle=Number(o.angle)||0;if(o.type==='solid'){el.className=`platform ${o.kind||'platform'} stage-obj`;Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px',transform:`rotate(${angle}deg)`})}
 else if(o.type==='hazard'&&o.kind==='spike'){el.className=`spike ${o.dir||'up'} stage-obj`;Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px',transform:`rotate(${angle}deg)`});el.style.setProperty('--sw',w+'px');el.style.setProperty('--sh',h+'px')}
 else if(o.type==='hazard'&&o.kind==='lava'){el.className='platform lava stage-obj';Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});el.dataset.hazard='lava'}
 else return null;el.dataset.object=JSON.stringify(o);arena.appendChild(el);return el}
function spawnPlayer(){const s=currentStage||stages[currentStageIndex],sp=s?.spawn||{x:30,y:272},size=getArenaSize(s);player={x:clamp(Number(sp.x)||30,0,Math.max(0,size.width-PLAYER_W)),y:clamp(Number(sp.y)||272,0,Math.max(0,size.height-PLAYER_H)),vx:0,vy:0,onGround:false,dead:false,rotation:0};jumpQueued=false;invincible=false;playerEl.classList.remove('dead','jumping');spawnEl.style.left=player.x+'px';spawnEl.style.top=(player.y+PLAYER_H+4)+'px';syncPlayerDOM();setStatus('Aktif','ok')}
function syncSpawnMarker(){const s=currentStage?.spawn||{x:34,y:272};spawnEl.style.left=(Number(s.x)||0)+'px';spawnEl.style.top=((Number(s.y)||0)+PLAYER_H+4)+'px'}
function syncPlayerDOM(){playerEl.style.left=player.x+'px';playerEl.style.top=player.y+'px';playerEl.style.transform=`rotate(${player.rotation}deg)`}

/* ---------- COLLISION ENGINE ---------- */
function rectsOverlap(a,b){return !(a.right<=b.left||a.left>=b.right||a.bottom<=b.top||a.top>=b.bottom)}
function getPlayerRect(){return{left:player.x+PLAYER_HITBOX.x,top:player.y+PLAYER_HITBOX.y,right:player.x+PLAYER_HITBOX.x+PLAYER_HITBOX.w,bottom:player.y+PLAYER_HITBOX.y+PLAYER_HITBOX.h,w:PLAYER_HITBOX.w,h:PLAYER_HITBOX.h}}
function playerPoly(){const r=getPlayerRect();return[{x:r.left,y:r.top},{x:r.right,y:r.top},{x:r.right,y:r.bottom},{x:r.left,y:r.bottom}]}
function centerOf(poly){return poly.reduce((a,q)=>({x:a.x+q.x/poly.length,y:a.y+q.y/poly.length}),{x:0,y:0})}
function rotatePoly(poly,c,rad){const co=Math.cos(rad),si=Math.sin(rad);return poly.map(p=>({x:c.x+(p.x-c.x)*co-(p.y-c.y)*si,y:c.y+(p.x-c.x)*si+(p.y-c.y)*co}))}
function polyAxes(poly){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;out.push({x:-dy/len,y:dx/len})}return out}
function projectPoly(poly,axis){let min=Infinity,max=-Infinity;for(const p of poly){const v=p.x*axis.x+p.y*axis.y;min=Math.min(min,v);max=Math.max(max,v)}return{min,max}}
function sat(a,b){let smallest=Infinity,axis=null;for(const ax of [...polyAxes(a),...polyAxes(b)]){const pa=projectPoly(a,ax),pb=projectPoly(b,ax),overlap=Math.min(pa.max,pb.max)-Math.max(pa.min,pb.min);if(overlap<=0)return null;if(overlap<smallest){smallest=overlap;axis={x:ax.x,y:ax.y}}}const ac=centerOf(a),bc=centerOf(b);if((bc.x-ac.x)*axis.x+(bc.y-ac.y)*axis.y<0){axis.x*=-1;axis.y*=-1}return{depth:smallest,axis}}
function boxPolygon(x,y,w,h,angleDeg=0){const p=[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];return angleDeg?rotatePoly(p,{x:x+w/2,y:y+h/2},Number(angleDeg)*Math.PI/180):p}
function trianglePolygon(x,y,w,h,dir='up',inset=0,angleDeg=0){const i=clamp(Number(inset)||0,0,Math.min(w,h)/2);let p=dir==='down'?[{x:x+i,y:y+i},{x:x+w-i,y:y+i},{x:x+w/2,y:y+h-i}]:dir==='left'?[{x:x+w-i,y:y+i},{x:x+w-i,y:y+h-i},{x:x+i,y:y+h/2}]:dir==='right'?[{x:x+i,y:y+i},{x:x+w-i,y:y+h/2},{x:x+i,y:y+h-i}]:[{x:x+w/2,y:y+i},{x:x+w-i,y:y+h-i},{x:x+i,y:y+h-i}];return angleDeg?rotatePoly(p,{x:x+w/2,y:y+h/2},Number(angleDeg)*Math.PI/180):p}
function localLayoutBox(el){let x=0,y=0,node=el;while(node&&node!==arena){x+=node.offsetLeft||0;y+=node.offsetTop||0;node=node.offsetParent}return{x,y,w:el.offsetWidth,h:el.offsetHeight}}
function domRotationScale(el){const t=getComputedStyle(el).transform;if(!t||t==='none')return{angle:0,sx:1,sy:1};try{const m=new DOMMatrixReadOnly(t);return{angle:Math.atan2(m.b,m.a),sx:Math.hypot(m.a,m.b)||1,sy:Math.hypot(m.c,m.d)||1}}catch{return{angle:0,sx:1,sy:1}}}
function domSolidPolygon(el){const b=localLayoutBox(el),{angle,sx,sy}=domRotationScale(el),w=b.w*sx,h=b.h*sy,c={x:b.x+b.w/2,y:b.y+b.h/2};const p=[{x:c.x-w/2,y:c.y-h/2},{x:c.x+w/2,y:c.y-h/2},{x:c.x+w/2,y:c.y+h/2},{x:c.x-w/2,y:c.y+h/2}];return angle?rotatePoly(p,c,angle):p}
function stageCollider(el){let o;try{o=JSON.parse(el.dataset.object||'{}')}catch{return null}const x=Number(o.x)||0,y=Number(o.y)||0,w=Number(o.w)||100,h=Number(o.h)||20,angle=Number(o.angle)||0;if(o.type==='solid')return{el,obj:o,shape:'box',poly:boxPolygon(x,y,w,h,angle),solid:true,hazard:false};if(o.type==='hazard'&&o.kind==='spike')return{el,obj:o,shape:'triangle',poly:trianglePolygon(x,y,w,h,o.dir||'up',Number(o.collider?.inset)||3,angle),solid:false,hazard:true};if(o.type==='hazard'&&o.kind==='lava')return{el,obj:o,shape:'box',poly:boxPolygon(x,y,w,h),solid:false,hazard:true};return null}
function userColliders(){const arr=[];userEls.querySelectorAll('*').forEach(el=>{if(el.closest('#hud'))return;const cs=getComputedStyle(el),b=localLayoutBox(el);if(cs.position!=='absolute'||b.w<=0||b.h<=0)return;arr.push({el,shape:'box',poly:domSolidPolygon(el),solid:true,hazard:false})});return arr}
function getColliders(){return[...arena.querySelectorAll('.stage-obj')].map(stageCollider).filter(Boolean).concat(userColliders())}
function axisAlignedRectFromPoly(poly){const xs=poly.map(p=>p.x),ys=poly.map(p=>p.y);return{left:Math.min(...xs),right:Math.max(...xs),top:Math.min(...ys),bottom:Math.max(...ys)}}
function overlapHorizontal(r,s){return r.right>s.left&&r.left<s.right} function overlapVertical(r,s){return r.bottom>s.top&&r.top<s.bottom}
function resolveAxisSolid(prevRect,nextRect,c){const s=axisAlignedRectFromPoly(c.poly),down=nextRect.bottom>prevRect.bottom,up=nextRect.top<prevRect.top,right=nextRect.right>prevRect.right,left=nextRect.left<prevRect.left;if(down&&prevRect.bottom<=s.top+0.5&&nextRect.bottom>=s.top&&overlapHorizontal(nextRect,s)){player.y=s.top-PLAYER_HITBOX.y-PLAYER_HITBOX.h;player.vy=0;player.onGround=true;player.rotation=0;playerEl.classList.remove('jumping');return'top'}if(up&&prevRect.top>=s.bottom-0.5&&nextRect.top<=s.bottom&&overlapHorizontal(nextRect,s)){player.y=s.bottom-PLAYER_HITBOX.y;player.vy=0;return'bottom'}if(right&&prevRect.right<=s.left+0.5&&nextRect.right>=s.left&&overlapVertical(nextRect,s)){player.x=s.left-PLAYER_HITBOX.x-PLAYER_HITBOX.w;player.vx=0;return'left'}if(left&&prevRect.left>=s.right-0.5&&nextRect.left<=s.right&&overlapVertical(nextRect,s)){player.x=s.right-PLAYER_HITBOX.x;player.vx=0;return'right'}return null}
function resolveRotatedSolid(hit){player.x-=hit.axis.x*hit.depth;player.y-=hit.axis.y*hit.depth;if(Math.abs(hit.axis.y)>=Math.abs(hit.axis.x)){if(hit.axis.y<0){player.onGround=true;player.vy=0;player.rotation=0;playerEl.classList.remove('jumping')}else if(player.vy<0)player.vy=0}else player.vx=0}
function checkHazards(poly,colliders){for(const c of colliders)if(c.hazard&&sat(poly,c.poly)){killPlayer();return true}return false}
function checkGoal(){const g=currentStage?.goal||{x:640,y:60};const r={left:Number(g.x)||0,top:Number(g.y)||0,right:(Number(g.x)||0)+38,bottom:(Number(g.y)||0)+54};if(rectsOverlap(getPlayerRect(),r))showWin()}
function updatePhysics(){if(player.dead||inputMode!=='play')return;const prevRect=getPlayerRect();let moving=false;if(keys.ArrowLeft||keys.a){player.vx=-MOVE_SPD;moving=true}if(keys.ArrowRight||keys.d){player.vx=MOVE_SPD;moving=true}if(!moving)player.vx=0;if(jumpQueued&&player.onGround){player.vy=JUMP_VEL;player.onGround=false;playerEl.classList.add('jumping')}jumpQueued=false;player.vy=Math.min(MAX_FALL,player.vy+GRAVITY);player.x+=player.vx;player.y+=player.vy;const size=getArenaSize();if(player.x<0){player.x=0;player.vx=0}if(player.x+PLAYER_W>size.width){player.x=size.width-PLAYER_W;player.vx=0}if(player.y<0){player.y=0;player.vy=0}player.onGround=false;const colliders=getColliders();for(const c of colliders){if(!c.solid)continue;if(c.shape==='box'&&Math.abs(Number(c.obj?.angle||0))<.001){if(resolveAxisSolid(prevRect,getPlayerRect(),c))continue}const hit=sat(playerPoly(),c.poly);if(hit)resolveRotatedSolid(hit)}if(checkHazards(playerPoly(),colliders))return;if(player.y>size.height+60){killPlayer();return}if(!player.onGround)player.rotation=(player.rotation+ (player.vx!==0?6:4))%360;checkGoal();coordsEl.textContent=`x:${Math.round(player.x)} y:${Math.round(player.y)}`;syncPlayerDOM()}

/* ---------- FIXED STEP LOOP ---------- */
function gameLoop(now){if(!gameRunning)return;const dt=Math.min((now-lastFrameTime)/1000,MAX_FRAME_DT);lastFrameTime=now;physicsAccumulator+=dt;let steps=0;while(physicsAccumulator>=FIXED_DT&&steps<MAX_STEPS_PER_FRAME){updatePhysics();physicsAccumulator-=FIXED_DT;steps++}animFrame=requestAnimationFrame(gameLoop)}
function startGame(){gameRunning=true;physicsAccumulator=0;lastFrameTime=performance.now();if(animFrame)cancelAnimationFrame(animFrame);animFrame=requestAnimationFrame(gameLoop);setStatus('Aktif','ok')}
function stopGame(){gameRunning=false;physicsAccumulator=0;if(animFrame){cancelAnimationFrame(animFrame);animFrame=null}keys={};jumpQueued=false}
function setStatus(msg,state){if(statusText)statusText.textContent=msg;if(statusDot)statusDot.classList.toggle('dead',state==='dead')}
function killPlayer(){if(player.dead||invincible)return;player.dead=true;deathCount++;deathCountEl.textContent=deathCount;playerEl.classList.add('dead');setStatus('Mati!','dead');deathFlash.classList.add('active');setTimeout(()=>{deathFlash.classList.remove('active');if(gameRunning||currentStage)spawnPlayer()},320)}

/* ---------- CODE EXECUTION ---------- */
const FORBIDDEN_PATTERNS=[{re:/<script[\s>]/i,msg:'Tag <script> tidak diizinkan.'},{re:/javascript\s*:/i,msg:'Atribut javascript: tidak diizinkan.'},{re:/on\w+\s*=/i,msg:'Event handler inline tidak diizinkan.'},{re:/position\s*:\s*fixed/i,msg:'position:fixed tidak diizinkan.'},{re:/!important/i,msg:'!important tidak diizinkan.'},{re:/<iframe/i,msg:'iframe tidak diizinkan.'},{re:/<embed/i,msg:'embed tidak diizinkan.'},{re:/<object/i,msg:'object tidak diizinkan.'},{re:/expression\s*\(/i,msg:'expression() tidak diizinkan.'},{re:/url\s*\(\s*data:/i,msg:'Data URLs tidak diizinkan.'}];
function validateCode(code){for(const p of FORBIDDEN_PATTERNS)if(p.re.test(code))return p.msg;return null}
function sanitizeStyle(s){return s.replace(/position\s*:\s*fixed[^;]*/gi,'').replace(/!important/gi,'').replace(/expression\s*\([^)]*\)/gi,'')}
function runCode(){const code=codeInput.value.trim(),err=code?validateCode(code):null;if(err){showWarn(err);return}closeWarn();spawnPlayer();userEls.innerHTML='';try{const tmp=document.createElement('div');tmp.innerHTML=code;tmp.querySelectorAll('[style]').forEach(el=>el.setAttribute('style',sanitizeStyle(el.getAttribute('style')||'')));tmp.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{if(/^on/i.test(a.name))el.removeAttribute(a.name)}));for(const n of [...tmp.childNodes])userEls.appendChild(n.cloneNode(true));runCount++;runCountEl.textContent=runCount;toast('Kode berhasil dijalankan.');focusGame()}catch(e){showWarn('Kode HTML tidak valid: '+e.message);userEls.innerHTML=''}}
function showWarn(msg){warnText.textContent=msg;warnBanner.classList.add('visible')} function closeWarn(){warnBanner.classList.remove('visible')}
function confirmReset(){$('confirm-modal').classList.remove('hidden')} function closeConfirm(){$('confirm-modal').classList.add('hidden')}
function doReset(){closeConfirm();codeInput.value='';updateLineNumbers();userEls.innerHTML='';runCount=0;deathCount=0;runCountEl.textContent='0';deathCountEl.textContent='0';spawnPlayer();closeWarn();toast('Level di-reset.');focusGame()}

/* ---------- WIN / PROGRESSION ---------- */
function showWin(){stopGame();if(currentStage?.custom){toast('Custom stage selesai!');showScreen('editor-screen');renderEditor();return}const s=currentStage;completedStages.add(String(s.id));saveProgress();$('win-sub').textContent=`Stage ${s.id}: "${s.title}" selesai! Kematian: ${deathCount} | Run: ${runCount}x`;$('win-modal').classList.remove('hidden');spawnParticles();buildStageGrid()}
function nextStage(){$('win-modal').classList.add('hidden');if(currentStageIndex>=0&&currentStageIndex+1<stages.length)loadStage(currentStageIndex+1);else showStageScreen()}
function restartStage(){$('win-modal').classList.add('hidden');if(currentStage?.custom)loadCustomStage(currentStage,'editor');else loadStage(currentStageIndex,{preserveCode:true})}
function buildStageGrid(){const grid=$('stage-grid');if(!grid)return;grid.innerHTML='';if(!stages.length){grid.innerHTML='<div class="custom-empty">Belum ada level JSON yang berhasil dimuat. Buka Console untuk detail loader.</div>';return}stages.forEach((s,i)=>{const done=completedStages.has(String(s.id)),unlocked=isStageUnlocked(i),card=document.createElement('div');card.className=`stage-card${done?' completed':''}${!unlocked?' locked':''}${String(currentStage?.id)===String(s.id)?' current':''}`;card.innerHTML=`<div class="stage-num">${String(s.id).padStart(2,'0')}</div><div class="stage-diff ${stageDifficultyClass(s.diff)}">${String(s.diff||'medium').toUpperCase()}</div><div class="stage-title">${escapeHTML(s.title)}</div><div class="stage-description">${escapeHTML(s.description||'')}</div><div class="stage-lock">${done?'✓':!unlocked?'🔒':'▶'}</div>`;if(unlocked)card.onclick=()=>loadStage(i);grid.appendChild(card)})}
function buildCustomStageGrid(){const grid=$('custom-stage-grid');if(!grid)return;grid.innerHTML='';if(!customStages.length){grid.innerHTML='<div class="custom-empty">Belum ada stage custom. Buka <strong>Stage Editor</strong> untuk membuatnya.</div>';return}customStages.forEach(s=>{const card=document.createElement('div');card.className='stage-card custom-card';card.innerHTML=`<div class="stage-num">★</div><div class="stage-diff diff-med">CUSTOM</div><div class="stage-title">${escapeHTML(s.title)}</div><div class="stage-description">${escapeHTML(s.description||'')}</div><div class="custom-card-actions"><button type="button" data-action="play">▶ Mainkan</button><button type="button" data-action="edit">Edit</button><button type="button" data-action="delete">Hapus</button></div>`;card.querySelector('[data-action="play"]').onclick=e=>{e.stopPropagation();loadCustomStage(s,'stage-list')};card.querySelector('[data-action="edit"]').onclick=e=>{e.stopPropagation();openEditorForStage(s)};card.querySelector('[data-action="delete"]').onclick=e=>{e.stopPropagation();deleteCustomStage(s.id)};grid.appendChild(card)})}
function deleteCustomStage(id){if(!confirm('Hapus stage custom ini?'))return;customStages=customStages.filter(s=>String(s.id)!==String(id));saveCustomStages();buildCustomStageGrid();toast('Stage custom dihapus.')}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function resetProgress(){if(!confirm('Reset semua progres stage resmi dan stage custom?'))return;completedStages.clear();customStages=[];saveProgress();saveCustomStages();buildStageGrid();buildCustomStageGrid();toast('Progress berhasil di-reset.')}

/* ---------- INPUT ---------- */
function setInputMode(mode){inputMode=mode==='code'?'code':'play';localStorage.setItem('cp_input_mode',inputMode);document.body.classList.toggle('play-mode',inputMode==='play');document.body.classList.toggle('code-mode',inputMode==='code');$('play-mode-btn')?.classList.toggle('active',inputMode==='play');$('code-mode-btn')?.classList.toggle('active',inputMode==='code');syncSettingsUI();if(inputMode==='code'){keys={};jumpQueued=false;codeInput.focus()}else{codeInput.blur();hideAC();focusGame();syncBgm()}}
function focusGame(){const btns=document.querySelectorAll('#mode-toggle button,.game-screen .back-game,.game-screen .btn-menu');btns.forEach(b=>{if(document.activeElement===b)b.blur()});arena?.focus?.()}
function isTextInput(t){return !!t?.closest?.('textarea,input,select,[contenteditable="true"]')}
document.addEventListener('keydown',e=>{if(inputMode!=='play'||document.querySelector('.modal-overlay:not(.hidden)')||isTextInput(e.target))return;const k=e.key===' ' ? 'Space' : e.key;keys[k]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(k)){e.preventDefault();if(k==='ArrowUp'||k==='Space')jumpQueued=true}});
document.addEventListener('keyup',e=>{const k=e.key===' ' ? 'Space' : e.key;keys[k]=false});window.addEventListener('blur',()=>{keys={};jumpQueued=false});arena?.addEventListener('pointerdown',()=>{if(inputMode==='play')focusGame()});

/* ---------- ARENA SCALE / SPLITTER ---------- */
function rescaleArena(){const wrap=$('arena-wrapper');if(!wrap||!arena||$('game-screen')?.classList.contains('hidden'))return;const s=getArenaSize();const scale=Math.min(wrap.clientWidth/s.width,wrap.clientHeight/s.height,1);arena.style.left='50%';arena.style.top='50%';arena.style.transform=`translate(-50%,-50%) scale(${Math.max(.01,scale)})`}
(function(){const splitter=$('splitter'),left=$('left-panel'),wrap=$('arena-wrapper');let dragging=false;function splitTo(clientX){const mr=$('main').getBoundingClientRect();left.style.width=clamp(((clientX-mr.left)/mr.width)*100,20,80)+'%';rescaleArena()}splitter?.addEventListener('pointerdown',e=>{dragging=true;splitter.setPointerCapture?.(e.pointerId);splitter.classList.add('dragging');e.preventDefault()});splitter?.addEventListener('pointermove',e=>{if(dragging)splitTo(e.clientX)});splitter?.addEventListener('pointerup',()=>{dragging=false;splitter.classList.remove('dragging')});splitter?.addEventListener('pointercancel',()=>{dragging=false;splitter.classList.remove('dragging')});window.addEventListener('resize',rescaleArena);if(window.ResizeObserver&&wrap)new ResizeObserver(rescaleArena).observe(wrap);setTimeout(rescaleArena,0);setTimeout(rescaleArena,60);setTimeout(rescaleArena,250)})();

/* ---------- LINE NUMBERS + AUTOCOMPLETE ---------- */
function updateLineNumbers(){const n=Math.max(1,codeInput.value.split('\n').length);lineNumbers.innerHTML=Array.from({length:n},(_,i)=>i+1).join('<br>');lineNumbers.scrollTop=codeInput.scrollTop}

const AC_DB = [
  // ── HTML Tags ──
  { label:'div',       kind:'tag',  insert:'<div style="position:absolute; left:0px; bottom:0px; width:100px; height:20px; background:#2a4278;"></div>', detail:'Block container', doc:'Buat elemen kotak solid sebagai platform. Gunakan <code>position:absolute</code> dan properti <code>left</code>, <code>bottom</code>, <code>width</code>, <code>height</code>.' },
  { label:'div.platform', kind:'snip', insert:'<div style="position:absolute; left:${1:100}px; bottom:${2:120}px; width:${3:200}px; height:20px; background:#2a4278; border:1px solid #3a5a9a;"></div>', detail:'Platform snippet', doc:'Snippet cepat untuk membuat platform. Ganti nilai angka sesuai posisi yang diinginkan.' },
  { label:'div.bridge',   kind:'snip', insert:'<div style="position:absolute; left:${1:180}px; bottom:${2:440}px; width:${3:340}px; height:20px; background:#1a2a3e;"></div>', detail:'Jembatan datar', doc:'Platform lebar untuk menjembatani jurang. Sesuaikan <code>left</code> dan <code>width</code>.' },
  { label:'div.ladder',   kind:'snip', insert:'<div style="position:absolute; left:${1:200}px; bottom:${2:120}px; width:20px; height:${3:200}px; background:#1e2d4a;"></div>', detail:'Tangga vertikal', doc:'Kolom vertikal yang bisa digunakan sebagai tangga atau dinding pijakan.' },
  { label:'div.stair',    kind:'snip', insert:'<div style="position:absolute; left:${1:200}px; bottom:${2:100}px; width:80px; height:20px; background:#2a4278;"></div>\n<div style="position:absolute; left:${3:280}px; bottom:${4:160}px; width:80px; height:20px; background:#2a4278;"></div>\n<div style="position:absolute; left:${5:360}px; bottom:${6:220}px; width:80px; height:20px; background:#2a4278;"></div>', detail:'Tangga bertingkat (3 step)', doc:'Tiga platform bertingkat. Setiap step naik 60px secara default.' },
  { label:'div.wall',     kind:'snip', insert:'<div style="position:absolute; left:${1:300}px; bottom:0px; width:20px; height:${2:300}px; background:#1a2a3e;"></div>', detail:'Tembok vertikal', doc:'Dinding vertical. Atur <code>height</code> untuk ketinggian tembok.' },
  { label:'p',            kind:'tag',  insert:'<p style="position:absolute; left:0px; bottom:0px; width:100px; height:20px;"></p>', detail:'Paragraph', doc:'Elemen paragraf — bisa digunakan sebagai platform tipis.' },
  { label:'section',      kind:'tag',  insert:'<section style="position:absolute; left:0px; bottom:0px; width:200px; height:40px;"></section>', detail:'Section block', doc:'Elemen section, solid seperti div.' },
  { label:'span',         kind:'tag',  insert:'<span style="position:absolute; left:0px; bottom:0px; width:60px; height:20px; display:block;"></span>', detail:'Inline (perlu display:block)', doc:'Span bersifat inline secara default, tambahkan <code>display:block</code> agar solid.' },

  // ── CSS Properties (sering dipakai dalam style="") ──
  { label:'position:absolute', kind:'prop', insert:'position:absolute; ', detail:'CSS property', doc:'Wajib untuk elemen dalam arena. Posisi relatif terhadap arena (720×360px).' },
  { label:'left',              kind:'prop', insert:'left:${1:100}px; ',   detail:'Posisi X dari kiri', doc:'Jarak dari tepi kiri arena. Rentang: 0 – 720px.' },
  { label:'bottom',            kind:'prop', insert:'bottom:${1:100}px; ', detail:'Posisi Y dari bawah', doc:'Jarak dari tepi bawah arena. Rentang: 0 – 360px. Lebih besar = lebih tinggi.' },
  { label:'top',               kind:'prop', insert:'top:${1:100}px; ',    detail:'Posisi Y dari atas', doc:'Jarak dari tepi atas arena. Rentang: 0 – 360px.' },
  { label:'right',             kind:'prop', insert:'right:${1:100}px; ',  detail:'Posisi X dari kanan', doc:'Jarak dari tepi kanan arena. Rentang: 0 – 720px.' },
  { label:'width',             kind:'prop', insert:'width:${1:200}px; ',  detail:'Lebar elemen', doc:'Lebar platform dalam piksel. Untuk arena 720px, 80–300px cukup untuk platform lompat.' },
  { label:'height',            kind:'prop', insert:'height:${1:20}px; ',  detail:'Tinggi elemen', doc:'Tinggi platform. 20px = platform tipis, 40px+ = platform tebal.' },
  { label:'background',        kind:'css',  insert:'background:${1:#2a4278}; ', detail:'Warna latar', doc:'Warna background elemen. Bisa hex (#2a4278), rgb, hsl, atau nama warna.' },
  { label:'background-color',  kind:'css',  insert:'background-color:${1:#2a4278}; ', detail:'Warna latar (longhand)', doc:'Sama seperti background, tapi khusus warna.' },
  { label:'border',            kind:'css',  insert:'border:${1:1px solid #3a5a9a}; ', detail:'Garis tepi', doc:'Border di sekeliling elemen. Format: tebal jenis warna.' },
  { label:'border-radius',     kind:'css',  insert:'border-radius:${1:4}px; ', detail:'Sudut membulat', doc:'Membuat sudut elemen membulat. 50% = lingkaran penuh.' },
  { label:'opacity',           kind:'css',  insert:'opacity:${1:0.8}; ', detail:'Transparansi (0-1)', doc:'Transparansi elemen. 0 = tak terlihat, 1 = sepenuhnya terlihat. Elemen tetap solid!' },
  { label:'transform:rotate',  kind:'css',  insert:'transform:rotate(${1:45}deg); ', detail:'Rotasi elemen', doc:'Memutar elemen. Collision akan mengikuti orientasi platform, bukan tetap memakai kotak axis-aligned.' },
  { label:'transform:scale',   kind:'css',  insert:'transform:scale(${1:1.5}); ', detail:'Skala elemen', doc:'Memperbesar/memperkecil tampilan elemen secara visual.' },
  { label:'display:block',     kind:'css',  insert:'display:block; ', detail:'Display block', doc:'Paksa elemen inline (span, a) menjadi block agar memiliki dimensi width/height.' },
  { label:'box-shadow',        kind:'css',  insert:'box-shadow:${1:0 0 10px rgba(91,156,246,0.5)}; ', detail:'Bayangan kotak', doc:'Memberi efek cahaya atau bayangan pada elemen. Tidak mempengaruhi collide.' },

  // ── CSS Color Values ──
  { label:'#2a4278', kind:'val', insert:'#2a4278', detail:'Biru tua (platform)', doc:'Warna platform standar — biru gelap.' },
  { label:'#1a2a3e', kind:'val', insert:'#1a2a3e', detail:'Biru lebih gelap (ground)', doc:'Warna ground/tanah — lebih gelap dari platform biasa.' },
  { label:'#162d3a', kind:'val', insert:'#162d3a', detail:'Biru-hijau (ice)', doc:'Warna es — memberikan nuansa lantai beku.' },
  { label:'#3a1a0e', kind:'val', insert:'#3a1a0e', detail:'Merah tua (lava)', doc:'Warna lava — merah kecokelatan gelap.' },
  { label:'#34d399', kind:'val', insert:'#34d399', detail:'Hijau (sukses/goal)', doc:'Warna hijau cerah seperti pintu tujuan.' },
  { label:'#5b9cf6', kind:'val', insert:'#5b9cf6', detail:'Biru accent', doc:'Biru terang seperti warna karakter.' },
  { label:'#a78bfa', kind:'val', insert:'#a78bfa', detail:'Ungu accent', doc:'Ungu pastel accent.' },
  { label:'#f97583', kind:'val', insert:'#f97583', detail:'Pink/merah muda', doc:'Merah muda cerah.' },
  { label:'rgba(255,255,255,0.2)', kind:'val', insert:'rgba(255,255,255,0.2)', detail:'Putih semi-transparan', doc:'Warna putih 20% opacity, berguna untuk efek glossy.' },

  // ── Platform Templates ──
  { label:'!platform-kiri',    kind:'snip', insert:'<!-- Platform sisi kiri -->\n<div style="position:absolute; left:180px; bottom:160px; width:120px; height:20px; background:#2a4278; border:1px solid #3a5a9a;"></div>', detail:'Platform kiri arena', doc:'Platform siap pakai di sisi kiri tengah arena.' },
  { label:'!platform-kanan',   kind:'snip', insert:'<!-- Platform sisi kanan -->\n<div style="position:absolute; left:420px; bottom:200px; width:120px; height:20px; background:#2a4278; border:1px solid #3a5a9a;"></div>', detail:'Platform kanan arena', doc:'Platform siap pakai di sisi kanan tengah arena.' },
  { label:'!platform-tengah',  kind:'snip', insert:'<!-- Platform tengah -->\n<div style="position:absolute; left:260px; bottom:240px; width:200px; height:20px; background:#1e2d4a; border:1px solid #2a4278;"></div>', detail:'Platform tengah arena', doc:'Platform horizontal tepat di tengah arena.' },
  { label:'!lompatan-pendek',  kind:'snip', insert:'<div style="position:absolute; left:180px; bottom:120px; width:80px; height:20px; background:#2a4278;"></div>\n<div style="position:absolute; left:320px; bottom:200px; width:80px; height:20px; background:#2a4278;"></div>\n<div style="position:absolute; left:460px; bottom:280px; width:80px; height:20px; background:#2a4278;"></div>', detail:'Batu loncatan (3 step naik)', doc:'Tiga stepping stone mengarah ke kiri-atas. Jarak antar platform ~60px horizontal dan 80px vertikal.' },
];

const acDropdown=$('ac-dropdown'),acList=$('ac-list'),acDoc=$('ac-doc'),acCount=$('ac-count');let acItems=[],acIdx=-1,acTriggerWord='';
function acVisible(){return acDropdown.classList.contains('visible')}function hideAC(){acDropdown.classList.remove('visible');acItems=[];acIdx=-1}
function getWordBefore(ta){const txt=ta.value,cur=ta.selectionStart;let i=cur;while(i>0&&/[\w\-:#.!<\/]/.test(txt[i-1]))i--;return{word:txt.substring(i,cur),start:i}}
function getCaretCoords(ta){const div=document.createElement('div'),style=getComputedStyle(ta);['fontFamily','fontSize','lineHeight','padding','paddingLeft','paddingTop','border','boxSizing','whiteSpace','wordSpacing','letterSpacing','tabSize'].forEach(p=>div.style[p]=style[p]);div.style.cssText+=';position:absolute;visibility:hidden;top:-9999px;left:-9999px;width:'+ta.offsetWidth+'px;height:auto;overflow:hidden;white-space:pre-wrap;word-break:break-all;';div.textContent=ta.value.substring(0,ta.selectionStart);const span=document.createElement('span');span.textContent='|';div.appendChild(span);document.body.appendChild(div);const tr=ta.getBoundingClientRect();const x=tr.left+(span.offsetLeft-ta.scrollLeft),y=tr.top+(span.offsetTop-ta.scrollTop);div.remove();return{x,y}}
function positionDropdown(x,y){const w=300,h=280,vw=innerWidth,vh=innerHeight;let l=Math.min(x,vw-w-8),t=y+18;if(t+h>vh-8)t=y-h;if(l<4)l=4;if(t<4)t=4;acDropdown.style.left=l+'px';acDropdown.style.top=t+'px'}
function computeSuggestions(word){if(!word)return[];const q=word.toLowerCase();return AC_DB.filter(i=>{const l=i.label.toLowerCase();return l.startsWith(q)||l.includes(q)}).sort((a,b)=>Number(!a.label.toLowerCase().startsWith(q))-Number(!b.label.toLowerCase().startsWith(q))||a.label.localeCompare(b.label)).slice(0,18)}
function highlightMatch(label,q){if(!q)return label;const i=label.toLowerCase().indexOf(q.toLowerCase());return i<0?label:label.slice(0,i)+`<span class="ac-match">${label.slice(i,i+q.length)}</span>`+label.slice(i+q.length)}
function kindIcon(kind){return`<div class="ac-icon ${kind}">${({tag:'T',prop:'P',val:'V',snip:'S',css:'C'})[kind]||'?'}</div>`}
function renderAC(items,word){acList.innerHTML='';acCount.textContent=items.length+' saran';items.forEach((item,i)=>{const d=document.createElement('div');d.className='ac-item'+(i===acIdx?' selected':'');d.innerHTML=`${kindIcon(item.kind)}<span class="ac-label">${highlightMatch(item.label,word)}</span><span class="ac-detail">${item.detail}</span>`;d.addEventListener('mousedown',e=>{e.preventDefault();acIdx=i;acConfirm()});d.addEventListener('mousemove',()=>{acIdx=i;renderAC(acItems,acTriggerWord)});acList.appendChild(d)});const sel=items[acIdx];acDoc.innerHTML=sel?.doc||'';acDoc.style.display=sel?.doc?'block':'none'}
function acConfirm(){if(!acVisible()||acIdx<0||acIdx>=acItems.length)return;const item=acItems[acIdx],txt=codeInput.value,cursor=codeInput.selectionStart;let ws=cursor;while(ws>0&&/[\w\-:#.!<\/]/.test(txt[ws-1]))ws--;const resolved=item.insert.replace(/\$\{(\d+):([^}]*)\}/g,(_,n,d)=>d).replace(/\$\d+/g,'');const before=txt.slice(0,ws),after=txt.slice(cursor);codeInput.value=before+resolved+after;const np=ws+resolved.length;codeInput.selectionStart=codeInput.selectionEnd=np;hideAC();updateLineNumbers();codeInput.focus()}
function acNavigate(dir){if(!acVisible()||!acItems.length)return;acIdx=(acIdx+dir+acItems.length)%acItems.length;renderAC(acItems,acTriggerWord);acList.querySelector('.selected')?.scrollIntoView({block:'nearest'})}
function triggerAC(){const{word}=getWordBefore(codeInput);acTriggerWord=word;if(word.length<1){hideAC();return}const s=computeSuggestions(word);if(!s.length){hideAC();return}acItems=s;if(acIdx<0||acIdx>=s.length)acIdx=0;const p=getCaretCoords(codeInput);positionDropdown(p.x,p.y);acDropdown.classList.add('visible');renderAC(s,word)}
codeInput.addEventListener('input',()=>{updateLineNumbers();triggerAC()});codeInput.addEventListener('scroll',()=>lineNumbers.scrollTop=codeInput.scrollTop);codeInput.addEventListener('keydown',e=>{if(acVisible()){if(e.key==='ArrowDown'){e.preventDefault();acNavigate(1);return}if(e.key==='ArrowUp'){e.preventDefault();acNavigate(-1);return}if(e.key==='Enter'){e.preventDefault();acConfirm();return}if(e.key==='Escape'){hideAC();return}if(e.key==='Tab'){e.preventDefault();acConfirm();return}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='r'){e.preventDefault();runCode()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='e'){e.preventDefault();confirmReset()}if(e.key==='Tab'&&!acVisible()){e.preventDefault();const s=codeInput.selectionStart;codeInput.value=codeInput.value.slice(0,s)+'  '+codeInput.value.slice(codeInput.selectionEnd);codeInput.selectionStart=codeInput.selectionEnd=s+2;updateLineNumbers()}requestAnimationFrame(triggerAC)});codeInput.addEventListener('click',()=>requestAnimationFrame(triggerAC));codeInput.addEventListener('blur',()=>setTimeout(hideAC,150));codeInput.addEventListener('focus',triggerAC);document.addEventListener('mousedown',e=>{if(!acDropdown.contains(e.target)&&e.target!==codeInput)hideAC()});

/* ---------- STAGE EDITOR ---------- */
function emptyEditor(){customEditor={id:null,title:'My Custom Stage',diff:'medium',description:'Buat jalurmu sendiri.',arena:{width:720,height:360},objects:[{type:'solid',kind:'ground',x:0,y:300,w:220,h:60,angle:0,collider:{shape:'box'}}],selected:null,tool:'edit',placeKind:'solid',spawn:{x:34,y:272},goal:{x:620,y:246}};resetEditorHistory()}
function editorState(){return{...deepClone(customEditor),selected:null}}
function resetEditorHistory(){editorHistory=[editorState()];editorHistoryIndex=0}
function commitEditorHistory(){const snap=editorState(),last=editorHistory[editorHistoryIndex];if(JSON.stringify(snap)===JSON.stringify(last))return;editorHistory=editorHistory.slice(0,editorHistoryIndex+1);editorHistory.push(snap);if(editorHistory.length>80)editorHistory.shift();editorHistoryIndex=editorHistory.length-1}
function restoreEditorSnapshot(snap){const keepSel=customEditor.selected;customEditor=deepClone(snap);customEditor.selected=keepSel!==null&&customEditor.objects[keepSel]?keepSel:null;clampEditorState();renderEditor()}
function undoEditor(){if(editorHistoryIndex<=0)return;editorHistoryIndex--;restoreEditorSnapshot(editorHistory[editorHistoryIndex]);toast('Undo.')}
function redoEditor(){if(editorHistoryIndex>=editorHistory.length-1)return;editorHistoryIndex++;restoreEditorSnapshot(editorHistory[editorHistoryIndex]);toast('Redo.')}
function clampEditorState(){customEditor.arena.width=clamp(Math.round(Number(customEditor.arena.width)||720),360,1400);customEditor.arena.height=clamp(Math.round(Number(customEditor.arena.height)||360),240,900);customEditor.objects.forEach(o=>{o.w=Math.max(8,Number(o.w)||40);o.h=Math.max(8,Number(o.h)||20);o.x=clamp(Number(o.x)||0,0,Math.max(0,customEditor.arena.width-o.w));o.y=clamp(Number(o.y)||0,0,Math.max(0,customEditor.arena.height-o.h));o.angle=Number(o.angle)||0});customEditor.spawn.x=clamp(Number(customEditor.spawn.x)||0,0,Math.max(0,customEditor.arena.width-PLAYER_W));customEditor.spawn.y=clamp(Number(customEditor.spawn.y)||0,0,Math.max(0,customEditor.arena.height-PLAYER_H));customEditor.goal.x=clamp(Number(customEditor.goal.x)||0,0,Math.max(0,customEditor.arena.width-38));customEditor.goal.y=clamp(Number(customEditor.goal.y)||0,0,Math.max(0,customEditor.arena.height-54))}
function setEditorTool(tool){customEditor.tool=tool;document.querySelectorAll('.editor-tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));renderEditor()}
function setEditorPlaceKind(kind){customEditor.placeKind=kind;document.querySelectorAll('.editor-place-kind').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));customEditor.tool='place';setEditorTool('place')}
function editorCoords(e){const ar=$('editor-arena').getBoundingClientRect(),scale=ar.width/customEditor.arena.width;return{x:clamp((e.clientX-ar.left)/scale,0,customEditor.arena.width),y:clamp((e.clientY-ar.top)/scale,0,customEditor.arena.height)}}
function newObject(kind,x,y){const o=kind==='solid'?{type:'solid',kind:'platform',x,y,w:120,h:20,angle:0,collider:{shape:'box'}}:{type:'hazard',kind,x,y,w:40,h:40,angle:0,dir:'up',collider:{shape:'triangle',inset:3}};if(kind==='lava'){o.w=120;o.h=30;o.collider={shape:'box'}}return o}
function addEditorObject(x,y,kind=customEditor.placeKind){const o=newObject(kind,Math.round(x/8)*8,Math.round(y/8)*8);customEditor.objects.push(o);customEditor.selected=customEditor.objects.length-1;commitEditorHistory();renderEditor()}
function deleteSelected(){const i=customEditor.selected;if(i===null||!customEditor.objects[i])return;customEditor.objects.splice(i,1);customEditor.selected=null;commitEditorHistory();renderEditor();toast('Objek dihapus.')}
function renderEditor(){const ar=$('editor-arena');if(!ar)return;clampEditorState();ar.style.width=customEditor.arena.width+'px';ar.style.height=customEditor.arena.height+'px';ar.querySelectorAll('.editor-obj').forEach(e=>e.remove());customEditor.objects.forEach((o,i)=>{const d=document.createElement('div');const cls=o.kind==='spike'?'spike':o.kind==='lava'?'lava':'solid';d.className='editor-obj '+cls+(i===customEditor.selected?' selected':'');d.style.left=o.x+'px';d.style.top=o.y+'px';d.style.width=o.w+'px';d.style.height=o.h+'px';d.style.transform=`rotate(${o.angle||0}deg)`;if(o.kind==='spike'){const p=o.dir==='down'?'polygon(0 0,100% 0,50% 100%)':o.dir==='left'?'polygon(100% 0,100% 100%,0 50%)':o.dir==='right'?'polygon(0 0,100% 50%,0 100%)':'polygon(50% 0,100% 100%,0 100%)';d.style.clipPath=p}d.dataset.index=i;d.addEventListener('pointerdown',e=>editorObjectPointerDown(e,i));ar.appendChild(d)});syncEditorMarkers();renderInspector();syncEditorControls();rescaleEditorArena()}
function syncEditorMarkers(){const s=$('editor-start-marker'),g=$('editor-goal-marker');if(s){s.style.left=customEditor.spawn.x+'px';s.style.top=customEditor.spawn.y+'px'}if(g){g.style.left=customEditor.goal.x+'px';g.style.top=customEditor.goal.y+'px'}}
function rescaleEditorArena(){const wrap=$('editor-canvas-wrap'),ar=$('editor-arena');if(!wrap||!ar)return;const scale=Math.min(wrap.clientWidth/customEditor.arena.width,wrap.clientHeight/customEditor.arena.height,1);ar.style.transform=`scale(${Math.max(.01,scale)})`;ar.style.transformOrigin='center center'}
function selectEditorObject(i,toggle=false){if(toggle&&customEditor.selected===i)customEditor.selected=null;else customEditor.selected=i;renderEditor()}
function editorObjectPointerDown(e,i){e.stopPropagation();if(customEditor.tool==='delete'){customEditor.selected=i;deleteSelected();return}if(customEditor.tool==='place'){selectEditorObject(i);return}customEditor.selected=i;const start=editorCoords(e),orig={...customEditor.objects[i]},prevState=editorState();editorDragging=true;const move=ev=>{const p=editorCoords(ev),o=customEditor.objects[i];o.x=clamp(Math.round((orig.x+p.x-start.x)/8)*8,0,customEditor.arena.width-o.w);o.y=clamp(Math.round((orig.y+p.y-start.y)/8)*8,0,customEditor.arena.height-o.h);renderEditor()};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);editorDragging=false;customEditor.selected=i;if(JSON.stringify(prevState)!==JSON.stringify(editorState()))commitEditorHistory();renderEditor()};addEventListener('pointermove',move);addEventListener('pointerup',up)}
function editorCanvasPointerDown(e){if(e.target.closest('.editor-obj,.editor-marker'))return;const p=editorCoords(e);if(customEditor.tool==='place'){addEditorObject(p.x,p.y);return}if(customEditor.tool==='delete'){return}customEditor.selected=null;renderEditor()}
function startMarkerDrag(e,kind){e.stopPropagation();if(customEditor.tool!=='edit')return;const marker=kind==='spawn'?customEditor.spawn:customEditor.goal,start=editorCoords(e),orig={...marker},before=editorState();const move=ev=>{const p=editorCoords(ev),target=kind==='spawn'?customEditor.spawn:customEditor.goal;target.x=clamp(Math.round((orig.x+p.x-start.x)/8)*8,0,customEditor.arena.width-(kind==='spawn'?PLAYER_W:38));target.y=clamp(Math.round((orig.y+p.y-start.y)/8)*8,0,customEditor.arena.height-(kind==='spawn'?PLAYER_H:54));renderEditor()};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);if(JSON.stringify(before)!==JSON.stringify(editorState()))commitEditorHistory();};addEventListener('pointermove',move);addEventListener('pointerup',up)}
function updateEditorNumber(id,key,min,max){const el=$(id);if(!el)return;el.value=customEditor[key];el.addEventListener('change',()=>{const v=clamp(Number(el.value)||0,min,max);customEditor[key]=v;commitEditorHistory();renderEditor()})}
function renderInspector(){const box=$('editor-inspector'),i=customEditor.selected;if(i===null||!customEditor.objects[i]){box.className='inspector muted';box.innerHTML='Pilih objek dengan <strong>Edit</strong>, lalu ubah propertinya di sini.';return}const o=customEditor.objects[i];box.className='inspector';box.innerHTML=`<div class="inspector-grid"><label>X<input id="ins-x" type="number" value="${o.x}"></label><label>Y<input id="ins-y" type="number" value="${o.y}"></label><label>Width<input id="ins-w" type="number" value="${o.w}"></label><label>Height<input id="ins-h" type="number" value="${o.h}"></label><label>Rotate<input id="ins-a" type="number" value="${o.angle||0}"></label><label>Direction<select id="ins-d"><option value="up" ${o.dir==='up'?'selected':''}>up</option><option value="down" ${o.dir==='down'?'selected':''}>down</option><option value="left" ${o.dir==='left'?'selected':''}>left</option><option value="right" ${o.dir==='right'?'selected':''}>right</option></select></label></div><div class="inspector-actions"><button type="button" onclick="deleteSelected()">Delete</button><button type="button" onclick="duplicateSelected()">Duplicate</button></div>`;[['x','ins-x'],['y','ins-y'],['w','ins-w'],['h','ins-h'],['angle','ins-a']].forEach(([k,id])=>$(id).addEventListener('change',e=>{o[k]=Number(e.target.value)||0;clampEditorState();commitEditorHistory();renderEditor()}));$('ins-d').addEventListener('change',e=>{o.dir=e.target.value;commitEditorHistory();renderEditor()})}
function syncEditorControls(){$('editor-title').value=customEditor.title;$('editor-diff').value=customEditor.diff;$('editor-desc').value=customEditor.description;$('editor-width').value=customEditor.arena.width;$('editor-height').value=customEditor.arena.height;document.querySelectorAll('.editor-tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===customEditor.tool));document.querySelectorAll('.editor-place-kind').forEach(b=>b.classList.toggle('active',b.dataset.kind===customEditor.placeKind))}
function editorSetMeta(){customEditor.title=$('editor-title').value.trim()||'My Custom Stage';customEditor.diff=$('editor-diff').value;customEditor.description=$('editor-desc').value.trim()||'Buat jalurmu sendiri.'}
function setEditorArenaWidth(v){customEditor.arena.width=clamp(Math.round(Number(v)||720),360,1400);commitEditorHistory();renderEditor()}
function setEditorArenaHeight(v){customEditor.arena.height=clamp(Math.round(Number(v)||360),240,900);commitEditorHistory();renderEditor()}
function copySelected(){const i=customEditor.selected;if(i===null||!customEditor.objects[i])return;editorClipboard=deepClone(customEditor.objects[i]);toast('Objek disalin.')}
function pasteSelected(){if(!editorClipboard)return;const o=deepClone(editorClipboard);o.x=clamp((o.x||0)+16,0,customEditor.arena.width-o.w);o.y=clamp((o.y||0)+16,0,customEditor.arena.height-o.h);customEditor.objects.push(o);customEditor.selected=customEditor.objects.length-1;commitEditorHistory();renderEditor();toast('Objek ditempel.')}
function duplicateSelected(){copySelected();pasteSelected()}
function openEditorForStage(stage){customEditor={id:stage.id||null,title:stage.title||'My Custom Stage',diff:stage.diff||'medium',description:stage.description||'',arena:stage.arena||{width:720,height:360},objects:deepClone(stage.objects||[]),selected:null,tool:'edit',placeKind:'solid',spawn:deepClone(stage.spawn||{x:34,y:272}),goal:deepClone(stage.goal||{x:620,y:246})};resetEditorHistory();showEditorScreen()}
function defaultEditor(){emptyEditor();showEditorScreen()}
function editorStageObject(){editorSetMeta();clampEditorState();return{id:customEditor.id||('custom-'+Date.now()),title:customEditor.title,custom:true,diff:customEditor.diff,description:customEditor.description,hint:'Stage custom. Gunakan HTML/CSS untuk membangun jalur lalu capai goal.',arena:deepClone(customEditor.arena),spawn:deepClone(customEditor.spawn),goal:deepClone(customEditor.goal),objects:deepClone(customEditor.objects)}}
function saveCustomStage(){const s=editorStageObject();const idx=customStages.findIndex(x=>String(x.id)===String(s.id));if(idx>=0)customStages[idx]=s;else customStages.push(s);customEditor.id=s.id;saveCustomStages();buildCustomStageGrid();commitEditorHistory();toast('Stage custom disimpan di perangkat.')}
function clearEditor(){if(!confirm('Bersihkan semua objek editor?'))return;emptyEditor();renderEditor();toast('Editor dibersihkan.')}
function exportEditorJSON(){const s=editorStageObject();delete s.custom;const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(s.title||'custom-stage').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function importStageJSON(){$('json-file-input').click()}
$('json-file-input')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const s=JSON.parse(rd.result);if(!s.title||!Array.isArray(s.objects))throw new Error('Format stage tidak valid');customEditor={id:s.id||null,title:s.title,diff:s.diff||'medium',description:s.description||'',arena:s.arena||{width:720,height:360},objects:deepClone(s.objects).filter(o=>o?.kind!=='diamond'),selected:null,tool:'edit',placeKind:'solid',spawn:s.spawn||{x:34,y:272},goal:s.goal||{x:620,y:246}};resetEditorHistory();renderEditor();toast('JSON berhasil di-import.')}catch(err){toast('Import gagal: '+err.message)}};rd.readAsText(f);e.target.value=''})
function playtestEditor(){const s=editorStageObject();playtestOrigin='editor';loadCustomStage(s,'editor')}
function editorKeyboard(e){const tag=e.target?.tagName;const typing=/INPUT|TEXTAREA|SELECT/.test(tag)||e.target?.isContentEditable;if(typing)return;const mod=e.ctrlKey||e.metaKey;const k=e.key.toLowerCase();if(mod&&k==='z'){e.preventDefault();e.shiftKey?redoEditor():undoEditor();return}if(mod&&k==='y'){e.preventDefault();redoEditor();return}if(mod&&k==='c'){e.preventDefault();copySelected();return}if(mod&&k==='v'){e.preventDefault();pasteSelected();return}if(mod&&k==='d'){e.preventDefault();duplicateSelected();return}if(mod&&k==='s'){e.preventDefault();saveCustomStage();return}if(e.key==='1'||k==='v'){setEditorTool('edit');return}if(e.key==='2'||k==='p'){setEditorTool('place');return}if(e.key==='3'||k==='x'){setEditorTool('delete');return}if((e.key==='Delete'||e.key==='Backspace')&&customEditor.selected!==null){e.preventDefault();deleteSelected()}}
document.addEventListener('keydown',editorKeyboard)
$('editor-arena')?.addEventListener('pointerdown',editorCanvasPointerDown);
$('editor-start-marker')?.addEventListener('pointerdown',e=>startMarkerDrag(e,'spawn'));
$('editor-goal-marker')?.addEventListener('pointerdown',e=>startMarkerDrag(e,'goal'));
$('editor-title')?.addEventListener('input',()=>{customEditor.title=$('editor-title').value});$('editor-diff')?.addEventListener('change',()=>{customEditor.diff=$('editor-diff').value});$('editor-desc')?.addEventListener('input',()=>{customEditor.description=$('editor-desc').value});
$('editor-width')?.addEventListener('change',e=>setEditorArenaWidth(e.target.value));$('editor-height')?.addEventListener('change',e=>setEditorArenaHeight(e.target.value));
window.addEventListener('resize',rescaleEditorArena)

/* ---------- PARTICLES ---------- */
function spawnParticles(){const colors=['#5b9cf6','#a78bfa','#34d399','#fbbf24'],cx=innerWidth/2,cy=innerHeight/2;for(let i=0;i<24;i++){const p=document.createElement('div');p.className='particle';const ang=Math.random()*Math.PI*2,dist=70+Math.random()*130,size=4+Math.random()*7;p.style.cssText=`left:${cx}px;top:${cy}px;width:${size}px;height:${size}px;background:${colors[i%colors.length]};--tx:${Math.cos(ang)*dist}px;--ty:${Math.sin(ang)*dist}px`;document.body.appendChild(p);setTimeout(()=>p.remove(),900)}}

/* ---------- INIT ---------- */
function init(){applyTheme();bgm?.addEventListener('error',()=>{if(bgmEnabled){bgmEnabled=false;localStorage.setItem('cp_bgm','off');syncSettingsUI();toast('File audio/background.opus belum ditambahkan.')}});syncBgm();updateLineNumbers();emptyEditor();setEditorTool('edit');renderEditor();showHome();loadAllStages();requestAnimationFrame(rescaleArena)}
init();
